# Generated by Django 5.2.17 on 2026-09-15 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSync',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('chain_height', models.PositiveIntegerField(null=True)),
                ('synced_at', models.DateTimeField(null=True)),
                ('last_attempt_at', models.DateTimeField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=160)),
                ('total_zatoshis', models.PositiveBigIntegerField(default=0)),
                ('spendable_zatoshis', models.PositiveBigIntegerField(default=0)),
                ('pending_zatoshis', models.PositiveBigIntegerField(default=0)),
                ('lease', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txid', models.CharField(max_length=64)),
                ('pool', models.PositiveSmallIntegerField()),
                ('output_index', models.PositiveIntegerField()),
                ('amount_zatoshis', models.PositiveBigIntegerField()),
                ('address', models.CharField(max_length=1024, null=True)),
                ('mined_height', models.PositiveIntegerField()),
                ('block_time', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='payments.paymentrequest')),
            ],
            options={
                'ordering': ['-block_time', '-id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'txid', 'pool', 'output_index'), name='unique_wallet_output')],
            },
        ),
    ]
