# Generated by Django 5.2.17 on 2026-09-24 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_walletsync_deposit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('recipient_address', models.CharField(max_length=1024)),
                ('amount_zatoshis', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('broadcast', 'Broadcast'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('txids', models.JSONField(default=list)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='unique_owner_send_key'), models.CheckConstraint(condition=models.Q(('amount_zatoshis__gte', 1), ('amount_zatoshis__lte', 2100000000000000)), name='valid_send_amount')],
            },
        ),
    ]
