# Generated by Django 5.2.17 on 2026-09-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_sendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrequest',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
