# Generated by Django 5.2.17 on 2026-09-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_sendrequest_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
